name: Release
on:
    push:
        branches:
            - "main"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 19
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm build

            - name: "Find Version in package.json"
              id: version
              run: |
                  echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

            - name: "Create Release"
              if: "startsWith(github.event.head_commit.message, 'release: ')"
              run: |
                  gh release create ${{ env.VERSION }} ./dist/*.js \
                    --title ${{ env.VERSION }} \
                    --notes "Grab this version of pyotr from [npm](https://npmjs.com/package/pyotr/v/${{ env.VERSION }})"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION: ${{ env.VERSION }}
